name: TEST

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        timeout-minutes: 2
